name: MamiyaSystem
version: @version@
main: com.github.rnlin.system.mamiya.MamiyaSystemPlugin
api-version: 1.15
authors: [rnlin]
description: Mamiya System

commands:
  wrc:
    description: It's main commands of this plugin.
    aliases: [worldriptidecanceller]
    usage:
      /<command>
      /wrc
    permisson: worldriptidecanceller.command.wr
    permission-message: You don't have the permission <permission>.
  ms:
    description: It's regen of this plugin.
    aliases: [mamiyasystem]
    usage:
      /<command>
    permisson: mamiya.system.command.mamiyasystem
    permission-message: You don't have the permission <permission>.

permissions:
  worldriptidecanceller.command.wrc:
    description: wrc commands
    default: op
  worldriptidecanceller.ignoreriptidecancel:
    description: ignore riptide cancel
    default: false
  mamiya.system.command.mamiyasystem:
    description: Allows you to use mamiyasystem command
    default: op
    children:
      mamiya.system.regen.command.*: true
  mamiya.system.regen.command.*:
    description: Allows you to use mamiyasystem all regenalation commands
    default: op
    children:
      mamiya.system.regen.command.regen: true
      mamiya.system.regen.command.undo: true
      mamiya.system.regen.command.redo: true
      mamiya.system.regen.command.help: true
  mamiya.system.regen.command.regen:
    description: Allows you to use regen command
    default: op
  mamiya.system.regen.command.undo:
    description: Allows you to use undo command
    default: op
  mamiya.system.regen.command.redo:
    description: Allows you to use redo command
    default: op
  mamiya.system.regen.command.help:
    description: Allows you to use help command
    default: op
